FROM python:3.11

WORKDIR /test_data_retrieval_app/

# Install Poetry
RUN curl -sSL https://install.python-poetry.org | POETRY_HOME=/opt/poetry python && \
    cd /usr/local/bin && \
    ln -s /opt/poetry/bin/poetry && \
    poetry config virtualenvs.create false

# Copy poetry.lock* in case it doesn't exist in the repo
COPY ./pyproject.toml ./poetry.lock* /test_data_retrieval_app/

# Allow installing dev dependencies to run tests
ARG INSTALL_DEV=false
RUN bash -c "if [ $INSTALL_DEV == 'true' ] ; then poetry install --no-root ; else poetry install --no-root --only main ; fi"

ENV PYTHONPATH=/test_data_retrieval_app

# Copy application code
COPY ./data_retrieval_app /test_data_retrieval_app/data_retrieval_app

# Copy test runner script
COPY ./start-tests.sh /test_data_retrieval_app/start-tests.sh

# Make the script executable
RUN chmod +x /test_data_retrieval_app/start-tests.sh

ENTRYPOINT ["/test_data_retrieval_app/start-tests.sh"]
