FROM python:3.12

ENV PYTHONUNBUFFERED=1

WORKDIR /test_data_retrieval_app/

# Ref: https://docs.astral.sh/uv/guides/integration/docker/#installing-uv
COPY --from=ghcr.io/astral-sh/uv:0.7.5 /uv /uvx /bin/

ENV PATH="/test_data_retrieval_app/.venv/bin:$PATH"

# Ref: https://docs.astral.sh/uv/guides/integration/docker/#compiling-bytecode
ENV UV_COMPILE_BYTECODE=1

# uv Cache
# Ref: https://docs.astral.sh/uv/guides/integration/docker/#caching
ENV UV_LINK_MODE=copy


# Install dependencies
# Ref: https://docs.astral.sh/uv/guides/integration/docker/#intermediate-layers
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project

ENV PYTHONPATH=/test_data_retrieval_app


COPY ./start-tests.sh ./pyproject.toml ./uv.lock /test_data_retrieval_app/

COPY ./data_retrieval_app /test_data_retrieval_app/data_retrieval_app

# Copy test runner script
COPY  /test_data_retrieval_app/start-tests.sh

# Make the script executable
RUN chmod +x /test_data_retrieval_app/start-tests.sh


# Sync the project
# Ref: https://docs.astral.sh/uv/guides/integration/docker/#intermediate-layers
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked


ENTRYPOINT ["/test_data_retrieval_app/start-tests.sh"]
