"""Added regex str and static bool to Modifier table

Revision ID: 1ce799793e74
Revises: 6d547b931353
Create Date: 2024-02-16 12:26:49.020288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ce799793e74'
down_revision: Union[str, None] = '6d547b931353'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modifier', sa.Column('static', sa.Boolean(), nullable=True))
    op.add_column('modifier', sa.Column('regex', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modifier', 'regex')
    op.drop_column('modifier', 'static')
    # ### end Alembic commands ###
