"""Updated Item, Modifier, currency table with removed updatedAt and added autoincrement surrogate key. Removed transaction table

Revision ID: 2976f535975d
Revises: 1ce799793e74
Create Date: 2024-02-16 13:19:46.180710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2976f535975d'
down_revision: Union[str, None] = '1ce799793e74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transaction_transactionId', table_name='transaction')
    op.drop_table('transaction')
    op.add_column('currency', sa.Column('currencyId', sa.Integer(), autoincrement=True, nullable=False))
    op.create_index(op.f('ix_currency_currencyId'), 'currency', ['currencyId'], unique=False)
    op.drop_column('currency', 'updatedAt')
    op.drop_column('item', 'updatedAt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('updatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('currency', sa.Column('updatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_currency_currencyId'), table_name='currency')
    op.drop_column('currency', 'currencyId')
    op.create_table('transaction',
    sa.Column('transactionId', sa.INTEGER(), server_default=sa.text('nextval(\'"transaction_transactionId_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('itemId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('accountName', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('currencyAmount', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('currencyName', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['accountName'], ['account.accountName'], name='transaction_accountName_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['currencyName'], ['currency.currencyName'], name='transaction_currencyName_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['itemId'], ['item.itemId'], name='transaction_itemId_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transactionId', name='transaction_pkey')
    )
    op.create_index('ix_transaction_transactionId', 'transaction', ['transactionId'], unique=False)
    # ### end Alembic commands ###
