"""Added autoincrement serial key Item, foreign keys in modifiertable and item, changed itemid name to gameitemid

Revision ID: 5ad713b2e498
Revises: 2976f535975d
Create Date: 2024-02-17 11:44:39.376308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ad713b2e498'
down_revision: Union[str, None] = '2976f535975d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'itemId')
    op.drop_column('item_modifier', 'itemId')
    op.add_column('item', sa.Column('gameItemId', sa.String(), nullable=False))
    op.create_index(op.f('ix_item_gameItemId'), 'item', ['gameItemId'], unique=False)
    op.add_column('item_modifier', sa.Column('itemId', sa.String(), nullable=False))
    op.add_column('item_modifier', sa.Column('gameItemId', sa.String(), nullable=False))
    op.create_index(op.f('ix_item_modifier_gameItemId'), 'item_modifier', ['gameItemId'], unique=False)
    op.drop_constraint('item_modifier_itemId_fkey', 'item_modifier', type_='foreignkey')
    op.create_primary_key(None, 'item', ['itemId', 'gameItemId'])
    op.create_foreign_key(None, 'item_modifier', 'item', ['itemId', 'gameItemId'], ['itemId', 'gameItemId'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item_modifier', type_='foreignkey')
    op.create_foreign_key('item_modifier_itemId_fkey', 'item_modifier', 'item', ['itemId'], ['itemId'], ondelete='CASCADE')
    op.drop_index(op.f('ix_item_modifier_gameItemId'), table_name='item_modifier')
    op.drop_column('item_modifier', 'gameItemId')
    op.drop_constraint(None, 'item', type_='unique')
    op.drop_index(op.f('ix_item_gameItemId'), table_name='item')
    op.drop_column('item', 'gameItemId')
    # ### end Alembic commands ###
