"""Created UniqueConstraint for (effect, position) in ItemModifier table

Revision ID: 79fcc084f06f
Revises: 3d1ef75d2a4d
Create Date: 2024-02-21 14:31:37.122544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79fcc084f06f'
down_revision: Union[str, None] = '3d1ef75d2a4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'modifier', ['effect', 'position'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modifier', type_='unique')
    # ### end Alembic commands ###
