"""Added loL

Revision ID: 060d5d2c8576
Revises: c6e3d491c8a5
Create Date: 2024-02-15 13:45:54.049863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '060d5d2c8576'
down_revision: Union[str, None] = 'c6e3d491c8a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loool',
    sa.Column('isLOL', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('isLOL')
    )
    op.create_index(op.f('ix_loool_isLOL'), 'loool', ['isLOL'], unique=False)
    op.drop_index('ix_lol_accountName', table_name='lol')
    op.drop_table('lol')
    op.alter_column('item', 'currencyAmount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=24),
               existing_nullable=True)
    op.alter_column('item_modifier', 'range',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=24),
               existing_nullable=True)
    op.alter_column('modifier', 'minRoll',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=24),
               existing_nullable=True)
    op.alter_column('modifier', 'maxRoll',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=24),
               existing_nullable=True)
    op.alter_column('transaction', 'currencyAmount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=24),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'currencyAmount',
               existing_type=sa.Float(precision=24),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('modifier', 'maxRoll',
               existing_type=sa.Float(precision=24),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('modifier', 'minRoll',
               existing_type=sa.Float(precision=24),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('item_modifier', 'range',
               existing_type=sa.Float(precision=24),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('item', 'currencyAmount',
               existing_type=sa.Float(precision=24),
               type_=sa.REAL(),
               existing_nullable=True)
    op.create_table('lol',
    sa.Column('accountName', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('isBEAST', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('accountName', name='lol_pkey')
    )
    op.create_index('ix_lol_accountName', 'lol', ['accountName'], unique=False)
    op.drop_index(op.f('ix_loool_isLOL'), table_name='loool')
    op.drop_table('loool')
    # ### end Alembic commands ###
