"""Added next_change_id table

Revision ID: 2bf07dcf3bb6
Revises: 042066a4f2b8
Create Date: 2024-03-25 18:37:08.196470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf07dcf3bb6'
down_revision: Union[str, None] = '042066a4f2b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('next_change_id',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('nextChangeId', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_next_change_id_id'), 'next_change_id', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_next_change_id_id'), table_name='next_change_id')
    op.drop_table('next_change_id')
    # ### end Alembic commands ###
