"""Changed subcategories column type from jsonb to string

Revision ID: 35b975af3c18
Revises: ee098521790e
Create Date: 2024-02-22 13:34:51.541122

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB


# revision identifiers, used by Alembic.
revision: str = "35b975af3c18"
down_revision: Union[str, None] = "ee098521790e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name="item_base_type",
        column_name="subCategory",
        type_=sa.String(),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name="item_base_type",
        column_name="subCategory",
        type_=JSONB(astext_type=sa.Text()),
    )
    # ### end Alembic commands ###
