"""Removed unique constraint for modifier table

Revision ID: 57d84b8d809e
Revises: 637572c1dee6
Create Date: 2024-03-27 15:36:10.854547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57d84b8d809e'
down_revision: Union[str, None] = '637572c1dee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('modifier_effect_position_key', 'modifier', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('modifier_effect_position_key', 'modifier', ['effect', 'position'])
    # ### end Alembic commands ###
