"""Added unique bool to modifier table

Revision ID: c1ff3b212b43
Revises: 43b8615411bb
Create Date: 2024-03-24 11:06:36.234366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1ff3b212b43'
down_revision: Union[str, None] = '43b8615411bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modifier', sa.Column('unique', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modifier', 'unique')
    # ### end Alembic commands ###
