"""Create a baseline migrations

Revision ID: c6e3d491c8a5
Revises: 6d547b931353
Create Date: 2024-02-15 13:39:03.181952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6e3d491c8a5'
down_revision: Union[str, None] = '6d547b931353'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lol',
    sa.Column('accountName', sa.String(), nullable=False),
    sa.Column('isBEAST', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('accountName')
    )
    op.create_index(op.f('ix_lol_accountName'), 'lol', ['accountName'], unique=False)
    op.alter_column('item', 'currencyAmount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=24),
               existing_nullable=True)
    op.alter_column('item_modifier', 'range',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=24),
               existing_nullable=True)
    op.alter_column('modifier', 'minRoll',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=24),
               existing_nullable=True)
    op.alter_column('modifier', 'maxRoll',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=24),
               existing_nullable=True)
    op.alter_column('transaction', 'currencyAmount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=24),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'currencyAmount',
               existing_type=sa.Float(precision=24),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('modifier', 'maxRoll',
               existing_type=sa.Float(precision=24),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('modifier', 'minRoll',
               existing_type=sa.Float(precision=24),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('item_modifier', 'range',
               existing_type=sa.Float(precision=24),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('item', 'currencyAmount',
               existing_type=sa.Float(precision=24),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_index(op.f('ix_lol_accountName'), table_name='lol')
    op.drop_table('lol')
    # ### end Alembic commands ###
