"""Create constraints for textrolls, maxroll, minroll

Revision ID: ee098521790e
Revises: 8e367f7f8609
Create Date: 2024-02-21 20:24:32.761582

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ee098521790e"
down_revision: Union[str, None] = "8e367f7f8609"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "maxroll_minroll",
        "modifier",
        "maxRoll >= minRoll",
    )
    op.create_check_constraint(
        "check_rolls_and_text",
        "modifier",
        "((minRoll IS NOT NULL AND maxRoll IS NOT NULL) AND textRoll IS NULL) OR (textRoll IS NOT NULL AND (minRoll IS NULL AND maxRoll IS NULL))",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
