"""Create constraints for textrolls, modifier.maxRoll, modifier.minRoll

Revision ID: ee098521790e
Revises: 8e367f7f8609
Create Date: 2024-02-21 20:24:32.761582

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import validates


# revision identifiers, used by Alembic.
revision: str = "ee098521790e"
down_revision: Union[str, None] = "8e367f7f8609"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        constraint_name="check_modifier_maxRoll_greaterThan_minRoll",
        table_name="modifier",
        condition='"modifier"."maxRoll" >= "modifier"."minRoll"',
    )

    op.create_check_constraint(
        constraint_name="check_modifier_if_minMaxRolls_then_not_textRoll_vv",
        table_name="modifier",
        condition='(("modifier"."minRoll" IS NOT NULL AND "modifier"."maxRoll" IS NOT NULL) AND "textRoll" IS NULL) OR ("textRoll" IS NOT NULL AND ("modifier"."minRoll" IS NULL AND "modifier"."maxRoll" IS NULL))',
    )

    op.create_check_constraint(
        constraint_name="check_modifier_if_or_not_minRoll_then_maxRoll_vv",
        table_name="modifier",
        condition='("modifier"."minRoll" IS NOT NULL AND "modifier"."maxRoll" IS NOT NULL) OR ("modifier"."minRoll" IS NULL AND "modifier"."maxRoll" IS NULL)',
    )
    
    op.create_check_constraint(
        constraint_name="check_modifier_static_conditions",
        table_name="modifier",
        condition='(modifier."static" AND modifier."textRoll" IS NULL AND (modifier."minRoll" IS NULL AND modifier."maxRoll" IS NULL)) OR (NOT modifier."static" AND (modifier."textRoll" IS NOT NULL OR (modifier."minRoll" IS NOT NULL AND modifier."maxRoll" IS NOT NULL)))',
    )


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "check_modifier_static_conditions", "modifier", type_="check"
    )
    op.drop_constraint(
        "check_modifier_if_or_not_minRoll_then_maxRoll_vv", "modifier", type_="check"
    )
    op.drop_constraint(
        "check_modifier_if_minMaxRolls_then_not_textRoll_vv", "modifier", type_="check"
    )
    op.drop_constraint(
        "check_modifier_maxRoll_greaterThan_minRoll", "modifier", type_="check"
    )
    # ### end Alembic commands ###
