"""Added pom_user table for login with pom_user

Revision ID: d388fc80c6f7
Revises: 99c06cd7231c
Create Date: 2024-08-14 14:53:16.814628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd388fc80c6f7'
down_revision: Union[str, None] = '99c06cd7231c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pom_user',
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashedPassword', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.Column('isSuperuser', sa.Boolean(), nullable=True),
    sa.Column('rateLimitTier', sa.SmallInteger(), nullable=True),
    sa.Column('isBanned', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_index(op.f('ix_user_email'), 'pom_user', ['email'], unique=True)
    op.create_index(op.f('ix_user_userId'), 'pom_user', ['userId'], unique=False)
    op.create_index(op.f('ix_user_username'), 'pom_user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='pom_user')
    op.drop_index(op.f('ix_user_userId'), table_name='pom_user')
    op.drop_index(op.f('ix_user_email'), table_name='pom_user')
    op.drop_table('pom_user')
    # ### end Alembic commands ###
