"""New revision test

Revision ID: 28b0800aa25d
Revises: 7be3677e7c93
Create Date: 2024-02-12 17:47:24.400798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28b0800aa25d'
down_revision: Union[str, None] = '7be3677e7c93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'currencyAmount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=24),
               existing_nullable=True)
    op.alter_column('item_modifier', 'range',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=24),
               existing_nullable=True)
    op.alter_column('modifier', 'minRoll',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=24),
               existing_nullable=True)
    op.alter_column('modifier', 'maxRoll',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=24),
               existing_nullable=True)
    op.alter_column('transaction', 'currencyAmount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=24),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'currencyAmount',
               existing_type=sa.Float(precision=24),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('modifier', 'maxRoll',
               existing_type=sa.Float(precision=24),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('modifier', 'minRoll',
               existing_type=sa.Float(precision=24),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('item_modifier', 'range',
               existing_type=sa.Float(precision=24),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('item', 'currencyAmount',
               existing_type=sa.Float(precision=24),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
