"""Removing modifier auto increment

Revision ID: 17daa1c96438
Revises: cc39d4eb113b
Create Date: 2026-05-09 16:05:14.813497

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.alembic.replaceable_objects.main import ReplaceableTrigger

# revision identifiers, used by Alembic.
revision: str = "17daa1c96438"
down_revision: Union[str, None] = "cc39d4eb113b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

modifier_id_trigger = ReplaceableTrigger(
    "increment_modifier_id",
    "modifier",
    """
    RETURNS trigger AS ${name}$
    DECLARE
        exists boolean;
    BEGIN
        exists := EXISTS(SELECT 1 FROM modifier WHERE "effect" = NEW.effect);
        IF NOT exists THEN
            NEW."modifierId" := nextval('modifier_id_seq');

        ELSIF exists THEN
            NEW."modifierId" := (SELECT "modifierId" FROM modifier WHERE "effect" = NEW.effect LIMIT 1);
        END IF;

        RETURN NEW;
    END;
    ${name}$ LANGUAGE plpgsql;
    """,
    """
    BEFORE INSERT ON {table}
	FOR EACH ROW
	EXECUTE FUNCTION {name}();
    """,
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # droping old item_modifier key
    op.drop_constraint(
        op.f("item_modifier_modifierId_fkey"), "item_modifier", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("item_modifier_modifierId_fkey1"), "item_modifier", type_="foreignkey"
    )

    # Dropping old modifier keys
    op.f("""ALTER TABLE modifier ALTER COLUMN "modifierId" DROP IDENTITY;""")
    op.drop_constraint(op.f("modifier_pkey"), "modifier", type_="primary")
    op.drop_constraint(
        op.f("modifier_modifierId_position_key"), "modifier", type_="unique"
    )

    # creating new keys
    op.create_primary_key("modifier_pkey", "modifier", ["modifierId", "position"])
    op.add_column(
        "item_modifier", sa.Column("position", sa.SmallInteger(), nullable=False)
    )
    op.create_foreign_key(
        "fk_item_modifier_modfierId_position",
        "item_modifier",
        "modifier",
        ["modifierId", "position"],
        ["modifierId", "position"],
        ondelete="CASCADE",
        onupdate="CASCADE",
    )

    op.execute("""
        UPDATE modifier AS m
        SET "modifierId" = "modifierId" + 10000;
    """)

    op.execute("""
        WITH subquery as (SELECT
            DENSE_RANK() OVER (
                ORDER BY m.effect
            ) AS newModifierId,
            m."position",
            m."modifierId" AS modifierId
        FROM modifier AS m
        ORDER BY newModifierId, m.position)

        UPDATE modifier AS m
        SET "modifierId" = sq.newModifierId
        FROM subquery AS sq
        WHERE "modifierId" = sq.modifierId;
    """)

    op.execute("CREATE SEQUENCE modifier_id_seq;")
    op.execute(
        """SELECT setval('modifier_id_seq', (SELECT MAX("modifierId") FROM modifier));"""
    )

    op.create_trigger(modifier_id_trigger)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_trigger(modifier_id_trigger)

    # dropping new modifier keys
    op.drop_constraint(
        op.f("fk_item_modifier_modfierId_position"), "item_modifier", type_="foreignkey"
    )
    op.drop_column("item_modifier", "position")
    op.drop_constraint(op.f("modifier_pkey"), "modifier", type_="primary")

    op.execute("""
        WITH subquery as (SELECT
            ROW_NUMBER() OVER(ORDER BY "modifierId", position ASC) AS newModifierId,
            m."position",
            m."modifierId" AS modifierId
        FROM modifier AS m
        ORDER BY newModifierId, m.position)
               
        UPDATE modifier AS m
        SET "modifierId" = sq.newModifierId
        FROM subquery AS sq
        WHERE "modifierId" = sq.modifierId 
        AND m.position = sq.position;
    """)

    op.execute("""
        DROP SEQUENCE modifier_id_seq;
    """)

    # adding old keys
    op.create_primary_key("modifier_pkey", "modifier", ["modifierId"])
    op.create_unique_constraint(
        op.f("modifier_modifierId_position_key"),
        "modifier",
        ["modifierId", "position"],
        postgresql_nulls_not_distinct=False,
    )

    op.create_foreign_key(
        "item_modifier_modifierId_fkey",
        "item_modifier",
        "modifier",
        ["modifierId"],
        ["modifierId"],
    )
    op.create_foreign_key(
        "item_modifier_modifierId_fkey1",
        "item_modifier",
        "modifier",
        ["modifierId"],
        ["modifierId"],
    )

    op.alter_column(
        "modifier",
        "modifierId",
        existing_type=sa.SMALLINT(),
        server_default=sa.Identity(
            always=False,
            start=1,
            increment=1,
            minvalue=1,
            maxvalue=32767,
            cycle=True,
            cache=1,
        ),
        existing_nullable=False,
    )
    op.execute(
        """SELECT setval(pg_get_serial_sequence('modifier', 'modifierId'), (SELECT MAX("modifierId") FROM modifier));"""
    )
    # ### end Alembic commands ###
