"""V8 Create baseline for hypertable refactor tables

Revision ID: 35736bccbe58
Revises: 
Create Date: 2024-11-13 11:49:35.765942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35736bccbe58'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('currencyId', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('createdHoursSinceLaunch', sa.SmallInteger(), nullable=False),
    sa.Column('valueInChaos', sa.Float(precision=4), nullable=False),
    sa.Column('tradeName', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('currencyId')
    )
    op.create_table('item_base_type',
    sa.Column('itemBaseTypeId', sa.SmallInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('baseType', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('subCategory', sa.Text(), nullable=True),
    sa.Column('relatedUniques', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('itemBaseTypeId'),
    sa.UniqueConstraint('baseType')
    )
    op.create_table('modifier',
    sa.Column('modifierId', sa.SmallInteger(), sa.Identity(always=False, start=1, increment=1, cycle=True), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('minRoll', sa.Float(precision=4), nullable=True),
    sa.Column('maxRoll', sa.Float(precision=4), nullable=True),
    sa.Column('implicit', sa.Boolean(), nullable=True),
    sa.Column('explicit', sa.Boolean(), nullable=True),
    sa.Column('delve', sa.Boolean(), nullable=True),
    sa.Column('fractured', sa.Boolean(), nullable=True),
    sa.Column('synthesised', sa.Boolean(), nullable=True),
    sa.Column('unique', sa.Boolean(), nullable=True),
    sa.Column('corrupted', sa.Boolean(), nullable=True),
    sa.Column('enchanted', sa.Boolean(), nullable=True),
    sa.Column('veiled', sa.Boolean(), nullable=True),
    sa.Column('static', sa.Boolean(), nullable=True),
    sa.Column('effect', sa.Text(), nullable=False),
    sa.Column('relatedUniques', sa.Text(), nullable=True),
    sa.Column('textRolls', sa.Text(), nullable=True),
    sa.Column('regex', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("\n            CASE\n                WHEN modifier.static = TRUE\n                THEN (\n                    modifier.effect NOT LIKE '%%#%%'\n                    )\n                ELSE (\n                    modifier.effect LIKE '%%#%%'\n                )\n            END\n            ", name='check_modifier_if_not_static_then_modifier_contains_hashtag'),
    sa.CheckConstraint(' modifier."maxRoll" >= modifier."minRoll" ', name='check_modifier_maxRoll_greaterThan_minRoll'),
    sa.CheckConstraint('\n            CASE\n                WHEN (modifier.static = TRUE)\n                THEN (\n                        (modifier."minRoll" IS NULL AND modifier."maxRoll" IS NULL)\n                        AND modifier."textRolls" IS NULL\n                        AND modifier.regex IS NULL\n                    )\n                ELSE (\n                        (\n                            (\n                                (modifier."minRoll" IS NOT NULL AND modifier."maxRoll" IS NOT NULL)\n                                AND modifier."textRolls" IS NULL\n                            )\n                            OR\n                            (\n                                (modifier."minRoll" IS  NULL AND modifier."maxRoll" IS  NULL)\n                                AND modifier."textRolls" IS NOT NULL\n                            )\n                        )\n                        AND modifier.regex IS NOT NULL\n                    )\n            END\n            ', name='check_modifier_if_static_else_check_rolls_and_regex'),
    sa.PrimaryKeyConstraint('modifierId'),
    sa.UniqueConstraint('modifierId', 'position')
    )
    op.create_table('pom_user',
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('rateLimitTier', sa.SmallInteger(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.Column('isSuperuser', sa.Boolean(), nullable=True),
    sa.Column('isBanned', sa.Boolean(), nullable=True),
    sa.Column('hashedPassword', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("username ~* '^[[:alnum:]_]+$'", name='check_username_letters_numbers_and_underscores'),
    sa.PrimaryKeyConstraint('userId'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('item',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('itemBaseTypeId', sa.SmallInteger(), nullable=False),
    sa.Column('createdHoursSinceLaunch', sa.SmallInteger(), nullable=False),
    sa.Column('league', sa.Text(), nullable=False),
    sa.Column('itemId', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('currencyId', sa.Integer(), nullable=False),
    sa.Column('ilvl', sa.SmallInteger(), nullable=False),
    sa.Column('prefixes', sa.SmallInteger(), nullable=True),
    sa.Column('suffixes', sa.SmallInteger(), nullable=True),
    sa.Column('foilVariation', sa.SmallInteger(), nullable=True),
    sa.Column('currencyAmount', sa.Float(precision=4), nullable=False),
    sa.Column('identified', sa.Boolean(), nullable=False),
    sa.Column('corrupted', sa.Boolean(), nullable=True),
    sa.Column('delve', sa.Boolean(), nullable=True),
    sa.Column('fractured', sa.Boolean(), nullable=True),
    sa.Column('synthesised', sa.Boolean(), nullable=True),
    sa.Column('replica', sa.Boolean(), nullable=True),
    sa.Column('searing', sa.Boolean(), nullable=True),
    sa.Column('tangled', sa.Boolean(), nullable=True),
    sa.Column('isRelic', sa.Boolean(), nullable=True),
    sa.Column('typeLine', sa.Text(), nullable=False),
    sa.Column('rarity', sa.Text(), nullable=False),
    sa.Column('influences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['currencyId'], ['currency.currencyId'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['itemBaseTypeId'], ['item_base_type.itemBaseTypeId'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('itemId')
    )
    op.create_index(op.f('ix_item_currencyId'), 'item', ['currencyId'], unique=False)
    op.create_index('ix_item_name_itemBaseTypeId_createdHoursSinceLaunch_league', 'item', ['name', 'itemBaseTypeId', 'createdHoursSinceLaunch', 'league'], unique=False)
    op.create_table('item_modifier',
    sa.Column('modifierId', sa.SmallInteger(), nullable=False),
    sa.Column('createdHoursSinceLaunch', sa.SmallInteger(), nullable=False),
    sa.Column('itemId', sa.BigInteger(), nullable=False),
    sa.Column('roll', sa.Float(precision=4), nullable=True),
    sa.ForeignKeyConstraint(['modifierId'], ['modifier.modifierId'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('itemId')
    )
    op.create_index('ix_item_modifierId_createdHoursSinceLaunch_itemId', 'item_modifier', ['modifierId', 'createdHoursSinceLaunch', 'itemId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_item_modifierId_createdHoursSinceLaunch_itemId', table_name='item_modifier')
    op.drop_table('item_modifier')
    op.drop_index('ix_item_name_itemBaseTypeId_createdHoursSinceLaunch_league', table_name='item')
    op.drop_index(op.f('ix_item_currencyId'), table_name='item')
    op.drop_table('item')
    op.drop_table('pom_user')
    op.drop_table('modifier')
    op.drop_table('item_base_type')
    op.drop_table('currency')
    # ### end Alembic commands ###
