"""Added checkconstraint for string in sqlalchemy model

Revision ID: 59a1d9f18849
Revises: d388fc80c6f7
Create Date: 2024-08-22 10:17:31.213183

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "59a1d9f18849"
down_revision: Union[str, None] = "d388fc80c6f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_email", table_name="pom_user")
    op.drop_index("ix_user_userId", table_name="pom_user")
    op.drop_index("ix_user_username", table_name="pom_user")
    op.create_index(op.f("ix_pom_user_email"), "pom_user", ["email"], unique=True)
    op.create_index(op.f("ix_pom_user_userId"), "pom_user", ["userId"], unique=False)
    op.create_index(op.f("ix_pom_user_username"), "pom_user", ["username"], unique=True)

    op.create_check_constraint(
        "check_username_letters_numbers_and_underscores",
        "pom_user",
        "username ~* '^[[:alnum:]_]+$'",
    )


# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pom_user_username"), table_name="pom_user")
    op.drop_index(op.f("ix_pom_user_userId"), table_name="pom_user")
    op.drop_index(op.f("ix_pom_user_email"), table_name="pom_user")
    op.create_index("ix_user_username", "pom_user", ["username"], unique=True)
    op.create_index("ix_user_userId", "pom_user", ["userId"], unique=False)
    op.create_index("ix_user_email", "pom_user", ["email"], unique=True)

    op.drop_constraint(
        "check_username_letters_numbers_and_underscores",
        "pom_user",
        type_="check",
    )
    # ### end Alembic commands ###
