"""Changed unidentified item table to aggregation version

Revision ID: 62c3fbcdc773
Revises: 0f3f15f56b7d
Create Date: 2025-03-04 11:47:43.525518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62c3fbcdc773'
down_revision: Union[str, None] = '0f3f15f56b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unidentified_item', sa.Column('nItems', sa.SmallInteger(), nullable=False))
    op.drop_column('unidentified_item', 'foilVariation')
    op.drop_column('unidentified_item', 'searing')
    op.drop_column('unidentified_item', 'replica')
    op.drop_column('unidentified_item', 'corrupted')
    op.drop_column('unidentified_item', 'synthesised')
    op.drop_column('unidentified_item', 'fractured')
    op.drop_column('unidentified_item', 'influences')
    op.drop_column('unidentified_item', 'tangled')
    op.drop_column('unidentified_item', 'delve')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unidentified_item', sa.Column('delve', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('unidentified_item', sa.Column('tangled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('unidentified_item', sa.Column('influences', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('unidentified_item', sa.Column('fractured', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('unidentified_item', sa.Column('synthesised', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('unidentified_item', sa.Column('corrupted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('unidentified_item', sa.Column('replica', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('unidentified_item', sa.Column('searing', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('unidentified_item', sa.Column('foilVariation', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.drop_column('unidentified_item', 'nItems')
    # ### end Alembic commands ###
