"""Removed created and updated at from the ItemBaseType table

Revision ID: 6d9ebe48cb1e
Revises: 59a1d9f18849
Create Date: 2024-09-27 16:53:09.315554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d9ebe48cb1e'
down_revision: Union[str, None] = '59a1d9f18849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_base_type', 'updatedAt')
    op.drop_column('item_base_type', 'createdAt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_base_type', sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('item_base_type', sa.Column('updatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
