"""Updated checkconstraint with underscore on username in pom_user

Revision ID: 874158ad90c6
Revises: 6d9ebe48cb1e
Create Date: 2024-10-02 10:36:06.201604

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "874158ad90c6"
down_revision: Union[str, None] = "6d9ebe48cb1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "check_username_letters_and_numbers", "pom_user", type_="check"
    )
    op.create_check_constraint(
        "check_username_letters_numbers_and_underscores",
        "pom_user",
        "username ~* '^[[:alnum:]_]+$'",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "check_username_letters_numbers_and_underscores", "pom_user", type_="check"
    )
    op.create_check_constraint(
        "check_username_letters_and_numbers",
        "pom_user",
        "username ~* '^[[:alnum:]]+$'",
    )
    # ### end Alembic commands ###
