"""Added gameItemId to identified items

Revision ID: cc39d4eb113b
Revises: e38727349f3f
Create Date: 2025-10-25 22:26:59.343322

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cc39d4eb113b"
down_revision: Union[str, None] = "e38727349f3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("item", sa.Column("gameItemId", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("item", "gameItemId")
    # ### end Alembic commands ###
