"""Created carantene modifier table

Revision ID: d789cc84cb4d
Revises: e38727349f3f
Create Date: 2025-11-18 19:44:38.570115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd789cc84cb4d'
down_revision: Union[str, None] = 'e38727349f3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carantene_modifier',
    sa.Column('caranteneModifierId', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1, cycle=True), nullable=False),
    sa.Column('effect', sa.Text(), nullable=False),
    sa.Column('relatedUnique', sa.Text(), nullable=False),
    sa.Column('implicit', sa.Boolean(), nullable=True),
    sa.Column('explicit', sa.Boolean(), nullable=True),
    sa.Column('delve', sa.Boolean(), nullable=True),
    sa.Column('fractured', sa.Boolean(), nullable=True),
    sa.Column('synthesised', sa.Boolean(), nullable=True),
    sa.Column('unique', sa.Boolean(), nullable=True),
    sa.Column('corrupted', sa.Boolean(), nullable=True),
    sa.Column('enchanted', sa.Boolean(), nullable=True),
    sa.Column('veiled', sa.Boolean(), nullable=True),
    sa.Column('mutated', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('caranteneModifierId')
    )
    op.alter_column('item', 'itemId',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=True, start=1, increment=1),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'itemId',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_table('carantene_modifier')
    # ### end Alembic commands ###
