"""Removed itemLevel

Revision ID: 13da6f882eff
Revises: 64d67fb763a2
Create Date: 2024-03-24 13:57:21.848125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13da6f882eff'
down_revision: Union[str, None] = '64d67fb763a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'itemLevel')
    op.add_column('modifier', sa.Column('textRolls', sa.String(), nullable=True))
    op.drop_column('modifier', 'textRoll')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modifier', sa.Column('textRoll', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('modifier', 'textRolls')
    op.add_column('item', sa.Column('itemLevel', sa.SMALLINT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
