"""Added updatedAt, createdAt in ItemModifier table

Revision ID: 8e367f7f8609
Revises: 79fcc084f06f
Create Date: 2024-02-21 14:41:06.566572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e367f7f8609'
down_revision: Union[str, None] = '79fcc084f06f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_modifier', sa.Column('createdAt', sa.DateTime(), nullable=False))
    op.add_column('item_modifier', sa.Column('updatedAt', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_modifier', 'updatedAt')
    op.drop_column('item_modifier', 'createdAt')
    # ### end Alembic commands ###
