"""Remove gameItemId primary key in item

Revision ID: 9d4c93e3592a
Revises: 35b975af3c18
Create Date: 2024-02-26 12:09:02.960739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d4c93e3592a'
down_revision: Union[str, None] = '35b975af3c18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("", "item", ["itemId", "gameItemId"])
    op.create_primary_key("", "item", ["itemId"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_primary_key("", "item", ["itemId, gameItemId"])
    # ### end Alembic commands ###
