from backend_api.app.api.routes.currency import currency_prefix
from backend_api.app.api.routes.item import item_prefix
from backend_api.app.api.routes.item_base_type import item_base_type_prefix
from backend_api.app.api.routes.league import league_prefix
from backend_api.app.api.routes.login import login_prefix
from backend_api.app.api.routes.modifier import modifier_prefix
from backend_api.app.api.routes.plot import plot_prefix
from backend_api.app.api.routes.test import test_prefix
from backend_api.app.api.routes.turnstile import turnstile_prefix
from backend_api.app.api.routes.unidentified_item import unidentified_item_prefix
from backend_api.app.api.routes.user import user_prefix
