from app.api.routes.account import account_prefix
from app.api.routes.currency import currency_prefix
from app.api.routes.item_base_type import item_base_type_prefix
from app.api.routes.item_modifier import item_modifier_prefix
from app.api.routes.item import item_prefix
from app.api.routes.modifier import modifier_prefix
from app.api.routes.stash import stash_prefix
from app.api.routes.plot import plot_prefix
from app.api.routes.turnstile import turnstile_prefix
