"""Rename currencyName to tradeName

Revision ID: 43b8615411bb
Revises: ea5bf65e52fd
Create Date: 2024-03-21 14:30:41.890500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43b8615411bb'
down_revision: Union[str, None] = 'ea5bf65e52fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency', sa.Column('tradeName', sa.String(), nullable=False))
    op.drop_index('ix_currency_currencyName', table_name='currency')
    op.create_index(op.f('ix_currency_tradeName'), 'currency', ['tradeName'], unique=False)
    op.drop_column('currency', 'currencyName')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency', sa.Column('currencyName', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_currency_tradeName'), table_name='currency')
    op.create_index('ix_currency_currencyName', 'currency', ['currencyName'], unique=False)
    op.drop_column('currency', 'tradeName')
    # ### end Alembic commands ###
