"""Upgraded Item with item level

Revision ID: 64d67fb763a2
Revises: 43b8615411bb
Create Date: 2024-03-22 11:11:53.040585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64d67fb763a2'
down_revision: Union[str, None] = '43b8615411bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('ilvl', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'ilvl')
    # ### end Alembic commands ###
