{
 "title": "Backend Data Retrieval",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Create item modifier table - Time diff ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "{job=\"vector\"} |= \"dataret.ext.timing\" |= \"create_item_modifier_table\" | json | keep timing_time_diff | line_format \"{{.timing_time_diff | float64}}\""
    }
   ]
  },
  {
   "title": "Process stream function: Time diff ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "{job=\"vector\"} |= \"dataret.ext.timing\" |= \"process_stream\" | json  | keep timing_time_diff | line_format \"{{.timing_time_diff | float64}}\""
    }
   ]
  },
  {
   "title": "Data retrieval - Errors",
   "type": "logs",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"vector\"} |= \"src-backend-data-retrieval\" != \"INFO\" | json | keep message, level, exc_info | line_format \"{{.level}}: {{.message}}: {{alignRight 50 .exc_info}}\""
    }
   ]
  },
  {
   "title": "Backend data retrieval simple",
   "type": "logs",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"vector\"} |= \"src-backend-data-retrieval\" | json | keep message, level | line_format \"{{.level}}: {{.message}}\"\n"
    }
   ]
  },
  {
   "title": "Backend data retrieval - Full error stack trace",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "{job=\"vector\"} |= \"src-backend-data-retrieval\" != \"INFO\" | json | keep message, level, exc_info | line_format \"{{.level}}: {{.message}}: {{.exc_info}}\""
    }
   ]
  }
 ]
}