{
 "title": "Backend API",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "API PATCH requests time length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"vector\"} |= \"pom_app.request\" |= \"PATCH\" | json | request_status_code != \"0\" | line_format \"{{.request_process_time_ms}}\""
    }
   ]
  },
  {
   "title": "API POST requests time length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "{job=\"vector\"} |= \"pom_app.request\" |= \"POST\" | json | request_status_code != \"0\" | line_format \"{{.request_process_time_ms}}\""
    }
   ]
  },
  {
   "title": "API GET requests time length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"vector\"} |= `pom_app.request` |= `GET` | json | request_status_code != `0` | line_format `{{.request_process_time_ms}}`"
    }
   ]
  },
  {
   "title": "Backend API - Requests",
   "type": "logs",
   "description": "Displays all information about general requests to the API.\n\nFilters status code \"0\" requests ",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"vector\"} |= `pom_app.request` | json | keep level, request_host, request_method, request_process_time_ms, request_status_code, request_url | line_format `{{.level}} {{.request_host}} {{.request_method}} {{.request_url}} {{.request_status_code}} {{.request_process_time_ms}}` | request_status_code != `0`"
    }
   ]
  },
  {
   "title": "Backend API - Errors (except from host:0.0.0.0)",
   "type": "logs",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"vector\"} |= \"src-backend-1\" != \"INFO\" or `0.0.0.0:80` | json | keep level, request_host, request_method, request_process_time_ms, request_status_code, request_url, message | line_format \"{{.level}} {{.request_host}} {{.request_method}} {{.request_url}} {{.request_status_code}} {{.request_process_time}} {{.message}}\" | request_status_code != \"0\""
    }
   ]
  },
  {
   "title": "Plot query request time length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "{job=\"vector\"}\n|= \"/api/api_v1/plot/\"\n| json\n| request_status_code != \"0\"\n| line_format \"{{.request_process_time_ms | float64}}\""
    }
   ]
  },
  {
   "title": "Plot Query Statement",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{job=\"vector\"} |= `pom_app.plot` or `SELECT` | json | keep message | line_format `{{.message}}`"
    }
   ]
  }
 ]
}