# Useful for development and testing 
services:
  db:
    ports: 
      - 5432:5432

    

  backend:
    ports:
      - 8080:80
    environment:
      - SERVER_HOST=http://${DOMAIN?Variable not set}
      - TESTING=True
      - DOMAIN=localhost:8080

  frontend:
    restart: "no"
    ports:
      - 80:80
    environment:
      - SERVER_HOST=http://${DOMAIN?Variable not set}
      - TESTING=True
      - DOMAIN=http://localhost
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://${DOMAIN?Variable not set}
        - NODE_ENV=development


networks:
  traefik-public:
    # For local dev, don't expect an external Traefik network
    external: false