# Useful for development and testing 
services:
  db:
    ports: 
      - 5432:5432

    

  backend:
    ports:
      - 80:80
    environment:
      - SERVER_HOST=http://${DOMAIN?Variable not set}
      - TESTING=True
      - DOMAIN=http://localhost




networks:
  traefik-public:
    # For local dev, don't expect an external Traefik network
    external: false