# Useful for development and testing 
services:
  db:
    ports: 
      - 5432:5432

    

  backend:
    ports:
      - 8888:80
    environment:
      - SERVER_HOST=http://${DOMAIN?Variable not set}
      - TESTING=True
      - DOMAIN=http://localhost

  # frontend:
  #   # restart: "no"
  #   ports:
  #     - 5173:5173
  #   environment:
  #     - SERVER_HOST=http://${DOMAIN?Variable not set}
  #     - TESTING=True
  #     - DOMAIN=http://localhost
  #   build:
  #     context: ./frontend
  #     args:
  #       - VITE_API_URL=http://${DOMAIN?Variable not set}
  #       - NODE_ENV=development


networks:
  traefik-public:
    # For local dev, don't expect an external Traefik network
    external: false