"""Made subcategory nullable

Revision ID: 8347f3b38e31
Revises: 57d84b8d809e
Create Date: 2024-03-27 18:02:28.715594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8347f3b38e31'
down_revision: Union[str, None] = '57d84b8d809e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item_base_type', 'subCategory',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item_base_type', 'subCategory',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
