"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.StashesService = exports.PlottingService = exports.ModifiersService = exports.LatestItemIdService = exports.LatestCurrencyIdService = exports.ItemsService = exports.ItemModifiersService = exports.ItemBaseTypesService = exports.DefaultService = exports.CurrenciesService = exports.AccountsService = exports.$WantedModifier = exports.$ValidationError = exports.$StashUpdate = exports.$StashCreate = exports.$Stash = exports.$PlotQuery = exports.$PlotData = exports.$ModifierUpdate = exports.$ModifierLimitations = exports.$ModifierCreate = exports.$Modifier = exports.$ItemUpdate = exports.$ItemSpecs = exports.$ItemModifierUpdate = exports.$ItemModifierCreate = exports.$ItemModifier = exports.$ItemCreate = exports.$ItemBaseTypeUpdate = exports.$ItemBaseTypeCreate = exports.$ItemBaseType = exports.$Item = exports.$Influences = exports.$HTTPValidationError = exports.$GroupedModifierByEffect = exports.$CurrencyUpdate = exports.$CurrencyCreate = exports.$Currency = exports.$BaseSpecs = exports.$AccountUpdate = exports.$AccountCreate = exports.$Account = exports.OpenAPI = exports.CancelError = exports.CancelablePromise = exports.ApiError = void 0;
/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
var ApiError_1 = require("./core/ApiError");
Object.defineProperty(exports, "ApiError", { enumerable: true, get: function () { return ApiError_1.ApiError; } });
var CancelablePromise_1 = require("./core/CancelablePromise");
Object.defineProperty(exports, "CancelablePromise", { enumerable: true, get: function () { return CancelablePromise_1.CancelablePromise; } });
Object.defineProperty(exports, "CancelError", { enumerable: true, get: function () { return CancelablePromise_1.CancelError; } });
var OpenAPI_1 = require("./core/OpenAPI");
Object.defineProperty(exports, "OpenAPI", { enumerable: true, get: function () { return OpenAPI_1.OpenAPI; } });
var _Account_1 = require("./schemas/$Account");
Object.defineProperty(exports, "$Account", { enumerable: true, get: function () { return _Account_1.$Account; } });
var _AccountCreate_1 = require("./schemas/$AccountCreate");
Object.defineProperty(exports, "$AccountCreate", { enumerable: true, get: function () { return _AccountCreate_1.$AccountCreate; } });
var _AccountUpdate_1 = require("./schemas/$AccountUpdate");
Object.defineProperty(exports, "$AccountUpdate", { enumerable: true, get: function () { return _AccountUpdate_1.$AccountUpdate; } });
var _BaseSpecs_1 = require("./schemas/$BaseSpecs");
Object.defineProperty(exports, "$BaseSpecs", { enumerable: true, get: function () { return _BaseSpecs_1.$BaseSpecs; } });
var _Currency_1 = require("./schemas/$Currency");
Object.defineProperty(exports, "$Currency", { enumerable: true, get: function () { return _Currency_1.$Currency; } });
var _CurrencyCreate_1 = require("./schemas/$CurrencyCreate");
Object.defineProperty(exports, "$CurrencyCreate", { enumerable: true, get: function () { return _CurrencyCreate_1.$CurrencyCreate; } });
var _CurrencyUpdate_1 = require("./schemas/$CurrencyUpdate");
Object.defineProperty(exports, "$CurrencyUpdate", { enumerable: true, get: function () { return _CurrencyUpdate_1.$CurrencyUpdate; } });
var _GroupedModifierByEffect_1 = require("./schemas/$GroupedModifierByEffect");
Object.defineProperty(exports, "$GroupedModifierByEffect", { enumerable: true, get: function () { return _GroupedModifierByEffect_1.$GroupedModifierByEffect; } });
var _HTTPValidationError_1 = require("./schemas/$HTTPValidationError");
Object.defineProperty(exports, "$HTTPValidationError", { enumerable: true, get: function () { return _HTTPValidationError_1.$HTTPValidationError; } });
var _Influences_1 = require("./schemas/$Influences");
Object.defineProperty(exports, "$Influences", { enumerable: true, get: function () { return _Influences_1.$Influences; } });
var _Item_1 = require("./schemas/$Item");
Object.defineProperty(exports, "$Item", { enumerable: true, get: function () { return _Item_1.$Item; } });
var _ItemBaseType_1 = require("./schemas/$ItemBaseType");
Object.defineProperty(exports, "$ItemBaseType", { enumerable: true, get: function () { return _ItemBaseType_1.$ItemBaseType; } });
var _ItemBaseTypeCreate_1 = require("./schemas/$ItemBaseTypeCreate");
Object.defineProperty(exports, "$ItemBaseTypeCreate", { enumerable: true, get: function () { return _ItemBaseTypeCreate_1.$ItemBaseTypeCreate; } });
var _ItemBaseTypeUpdate_1 = require("./schemas/$ItemBaseTypeUpdate");
Object.defineProperty(exports, "$ItemBaseTypeUpdate", { enumerable: true, get: function () { return _ItemBaseTypeUpdate_1.$ItemBaseTypeUpdate; } });
var _ItemCreate_1 = require("./schemas/$ItemCreate");
Object.defineProperty(exports, "$ItemCreate", { enumerable: true, get: function () { return _ItemCreate_1.$ItemCreate; } });
var _ItemModifier_1 = require("./schemas/$ItemModifier");
Object.defineProperty(exports, "$ItemModifier", { enumerable: true, get: function () { return _ItemModifier_1.$ItemModifier; } });
var _ItemModifierCreate_1 = require("./schemas/$ItemModifierCreate");
Object.defineProperty(exports, "$ItemModifierCreate", { enumerable: true, get: function () { return _ItemModifierCreate_1.$ItemModifierCreate; } });
var _ItemModifierUpdate_1 = require("./schemas/$ItemModifierUpdate");
Object.defineProperty(exports, "$ItemModifierUpdate", { enumerable: true, get: function () { return _ItemModifierUpdate_1.$ItemModifierUpdate; } });
var _ItemSpecs_1 = require("./schemas/$ItemSpecs");
Object.defineProperty(exports, "$ItemSpecs", { enumerable: true, get: function () { return _ItemSpecs_1.$ItemSpecs; } });
var _ItemUpdate_1 = require("./schemas/$ItemUpdate");
Object.defineProperty(exports, "$ItemUpdate", { enumerable: true, get: function () { return _ItemUpdate_1.$ItemUpdate; } });
var _Modifier_1 = require("./schemas/$Modifier");
Object.defineProperty(exports, "$Modifier", { enumerable: true, get: function () { return _Modifier_1.$Modifier; } });
var _ModifierCreate_1 = require("./schemas/$ModifierCreate");
Object.defineProperty(exports, "$ModifierCreate", { enumerable: true, get: function () { return _ModifierCreate_1.$ModifierCreate; } });
var _ModifierLimitations_1 = require("./schemas/$ModifierLimitations");
Object.defineProperty(exports, "$ModifierLimitations", { enumerable: true, get: function () { return _ModifierLimitations_1.$ModifierLimitations; } });
var _ModifierUpdate_1 = require("./schemas/$ModifierUpdate");
Object.defineProperty(exports, "$ModifierUpdate", { enumerable: true, get: function () { return _ModifierUpdate_1.$ModifierUpdate; } });
var _PlotData_1 = require("./schemas/$PlotData");
Object.defineProperty(exports, "$PlotData", { enumerable: true, get: function () { return _PlotData_1.$PlotData; } });
var _PlotQuery_1 = require("./schemas/$PlotQuery");
Object.defineProperty(exports, "$PlotQuery", { enumerable: true, get: function () { return _PlotQuery_1.$PlotQuery; } });
var _Stash_1 = require("./schemas/$Stash");
Object.defineProperty(exports, "$Stash", { enumerable: true, get: function () { return _Stash_1.$Stash; } });
var _StashCreate_1 = require("./schemas/$StashCreate");
Object.defineProperty(exports, "$StashCreate", { enumerable: true, get: function () { return _StashCreate_1.$StashCreate; } });
var _StashUpdate_1 = require("./schemas/$StashUpdate");
Object.defineProperty(exports, "$StashUpdate", { enumerable: true, get: function () { return _StashUpdate_1.$StashUpdate; } });
var _ValidationError_1 = require("./schemas/$ValidationError");
Object.defineProperty(exports, "$ValidationError", { enumerable: true, get: function () { return _ValidationError_1.$ValidationError; } });
var _WantedModifier_1 = require("./schemas/$WantedModifier");
Object.defineProperty(exports, "$WantedModifier", { enumerable: true, get: function () { return _WantedModifier_1.$WantedModifier; } });
var AccountsService_1 = require("./services/AccountsService");
Object.defineProperty(exports, "AccountsService", { enumerable: true, get: function () { return AccountsService_1.AccountsService; } });
var CurrenciesService_1 = require("./services/CurrenciesService");
Object.defineProperty(exports, "CurrenciesService", { enumerable: true, get: function () { return CurrenciesService_1.CurrenciesService; } });
var DefaultService_1 = require("./services/DefaultService");
Object.defineProperty(exports, "DefaultService", { enumerable: true, get: function () { return DefaultService_1.DefaultService; } });
var ItemBaseTypesService_1 = require("./services/ItemBaseTypesService");
Object.defineProperty(exports, "ItemBaseTypesService", { enumerable: true, get: function () { return ItemBaseTypesService_1.ItemBaseTypesService; } });
var ItemModifiersService_1 = require("./services/ItemModifiersService");
Object.defineProperty(exports, "ItemModifiersService", { enumerable: true, get: function () { return ItemModifiersService_1.ItemModifiersService; } });
var ItemsService_1 = require("./services/ItemsService");
Object.defineProperty(exports, "ItemsService", { enumerable: true, get: function () { return ItemsService_1.ItemsService; } });
var LatestCurrencyIdService_1 = require("./services/LatestCurrencyIdService");
Object.defineProperty(exports, "LatestCurrencyIdService", { enumerable: true, get: function () { return LatestCurrencyIdService_1.LatestCurrencyIdService; } });
var LatestItemIdService_1 = require("./services/LatestItemIdService");
Object.defineProperty(exports, "LatestItemIdService", { enumerable: true, get: function () { return LatestItemIdService_1.LatestItemIdService; } });
var ModifiersService_1 = require("./services/ModifiersService");
Object.defineProperty(exports, "ModifiersService", { enumerable: true, get: function () { return ModifiersService_1.ModifiersService; } });
var PlottingService_1 = require("./services/PlottingService");
Object.defineProperty(exports, "PlottingService", { enumerable: true, get: function () { return PlottingService_1.PlottingService; } });
var StashesService_1 = require("./services/StashesService");
Object.defineProperty(exports, "StashesService", { enumerable: true, get: function () { return StashesService_1.StashesService; } });
