name: Deploy to Production

on:
    push:
      branches:
        - 240-add-pytests-backend-to-github-actions
    pull_request:
      branches:
        - 240-add-pytests-backend-to-github-actions
        
jobs:
  deploy:
    runs-on:
      - self-hosted
      - production
    env:
      ENVIRONMENT: production
      DOMAIN: pathofmodifiers.com
      STACK_NAME: ${{ secrets.STACK_NAME_PRODUCTION }}
      API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
      POE_PUBLIC_STASH_TABS_AUTH_TOKEN: ${{ secrets.POE_PUBLIC_STASH_TABS_AUTH_TOKEN }}
      FIRST_SUPERUSER: ${{ secrets.FIRST_SUPERUSER }}
      FIRST_SUPERUSER_PASSWORD: ${{ secrets.FIRST_SUPERUSER_PASSWORD }}
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: docker compose -f docker-compose.yml --project-name pathofmodifiers build
        working-directory: ./src
      - run: docker compose -f docker-compose.yml --project-name pathofmodifiers up -d
        working-directory: ./src